apiVersion: v1
kind: Service
metadata:
  name: ndslabs-apiserver
  labels:
    component: ndslabs-apiserver
spec:
  selector:
    component: ndslabs-apiserver
  ports:
    - port: 30001
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ndslabs-apiserver
spec:
  replicas: 1
  selector:
    component: ndslabs-apiserver
  template:
    metadata:
      labels:
        component: ndslabs-apiserver
    spec:
      containers:
      - name: data-provider
        image: craigwillis/data-provider:NDS-748
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          protocol: TCP
        volumeMounts:
          - name: volumes
            mountPath: "/var/glfs/global"
      - name: ndslabs-apiserver
        image: craigwillis/apiserver:NDS-747
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 30001
          protocol: TCP
        volumeMounts:
          - name: volumes
            mountPath: "/var/glfs/global"
        env:
          - name: ETCD_ADDR
            value: "{{ IP_ADDR_MACHINE }}:4001"
          - name: KUBERNETES_ADDR
            value: "https://{{ IP_ADDR_MACHINE }}:6443"
          - name: CORS_ORIGIN_ADDR
            value: "{{ CORS_ORIGIN_ADDR }}"
          - name: SPEC_GIT_REPO
            value: "https://github.com/craig-willis/ndslabs-specs.git"
          - name: SPEC_GIT_BRANCH
            value: "terra-ref"
          - name: INGRESS
            value: "{{ INGRESS }}"
          - name: DOMAIN
            value: "{{ DOMAIN }}"
          - name: VOLUME_PATH
            value: "/var/glfs/global"
          - name: VOLUME_NAME
            value: "global"
          - name: SUPPORT_EMAIL
            value: "{{ SUPPORT_EMAIL }}"
          - name: REQUIRE_APPROVAL
            value: "{{ REQUIRE_APPROVAL }}"
          - name: SERVICE_TIMEOUT
            value: "10"
          - name: SHARED_VOLUME_PATH
            value: "/home/clowder/sites"
          - name: SHARED_VOLUME_NAME
            value: "terraref"
          - name: DATA_PROVIDER_URL
            value: "http://localhost:8083"
      volumes:
       - hostPath:
            path: "/var/glfs/global"
         name: volumes
