apiVersion: v1
kind: Service
metadata:
  name: ndslabs-apiserver
  labels:
    component: ndslabs-apiserver
spec:
  selector:
    component: ndslabs-apiserver
  ports:
    - port: 30001
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ndslabs-apiserver
spec:
  replicas: 1
  selector:
    component: ndslabs-apiserver
  template:
    metadata:
      labels:
        component: ndslabs-apiserver
    spec:
      containers:
      - name: ndslabs-apiserver
        image: ndslabs/apiserver:1.0.10
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 30001
          protocol: TCP
        volumeMounts:
          - name: volumes
            mountPath: "/ndslabs/home"
        env:
          - name: ETCD_ADDR
            value: "192.168.5.76:4001"
          - name: KUBERNETES_ADDR
            value: "https://192.168.5.76:6443"
          - name: CORS_ORIGIN_ADDR
            value: "http://www.terraref.ndslabs.org"
          - name: SPEC_GIT_REPO
            value: "https://github.com/nds-org/ndslabs-specs.git"
          - name: SPEC_GIT_BRANCH
            value: "terra-ref"
          - name: INGRESS
            value: "LoadBalancer"
          - name: DOMAIN
            value: "terraref.ndslabs.org"
          - name: VOLUME_PATH
            value: "/ndslabs/home"
          - name: VOLUME_NAME
            value: "global"
          - name: SUPPORT_EMAIL
            value: "terraref-support@lists.illinois.edu"
          - name: REQUIRE_APPROVAL
            value: "true"
          - name: SERVICE_TIMEOUT
            value: "10"
          - name: SHARED_VOLUME_PATH
            value: "/data/terraref/sites"
          - name: SHARED_VOLUME_NAME
            value: "terraref"
          - name: WORKBENCH_NAME
            value: "TERRA-REF Analysis Workbench"
          - name: SUPPORT_CHAT
            value: "https://terra-ref.slack.com/"
      volumes:
       - hostPath:
            path: "/ndslabs/home/"
         name: volumes
