apiVersion: v1
kind: Service
metadata:
  name: ndslabs-apiserver
  labels:
    component: ndslabs-apiserver
spec:
  selector:
    component: ndslabs-apiserver
  ports:
    - port: 30001
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ndslabs-apiserver
spec:
  replicas: 1
  selector:
    component: ndslabs-apiserver
  template:
    metadata:
      labels:
        component: ndslabs-apiserver
    spec:
      containers:
      - name: ndslabs-apiserver
        image: craigwillis/apiserver:NDS-517
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 30001
          protocol: TCP
        volumeMounts:
          - name: volumes
            mountPath: "/ndslabs/data/volumes"
        env:
          - name: ETCD_ADDR
            value: "$(NDSLABS_ETCD_PORT_4001_TCP_ADDR):4001"
          - name: KUBERNETES_ADDR
            value: "https://10.0.0.1:443"
          - name: CORS_ORIGIN_ADDR
            value: "http://www.azure.ndslabs.org"
          - name: SPEC_GIT_REPO
            value: "https://github.com/nds-org/ndslabs-specs.git"
          - name: SPEC_GIT_BRANCH
            value: "master"
          - name: INGRESS
            value: "LoadBalancer"
          - name: DOMAIN
            value: "azure.ndslabs.org"
          - name: VOLUME_PATH
            value: "/ndslabs/data/volumes"
          - name: VOLUME_NAME
            value: "global"
          - name: SUPPORT_EMAIL
            value: "willis8@illinois.edu"
          - name: REQUIRE_APPROVAL
            value: "true"
          - name: SERVICE_TIMEOUT
            value: "10"
          - name: TOKEN_PATH
            value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      volumes:
       - hostPath:
            path: "/ndslabs/data/volumes"
         name: volumes
