apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ndslabs-ingress
spec:
  rules:
  - host: www.terra-dev.ndslabs.org
    http:
      paths:
      - path: /api
        backend:
          serviceName: ndslabs-apiserver
          servicePort: 30001
      - path: /
        backend:
          serviceName: ndslabs-webui
          servicePort: 80
